# Generated by Django 3.2.18 on 2023-04-26 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Athlete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register_number', models.DecimalField(decimal_places=2, help_text='Athlete number.', max_digits=10, verbose_name='Athlete number')),
                ('name', models.CharField(help_text='Athlete name.', max_length=1000, verbose_name='Athlete name')),
                ('association', models.CharField(blank=True, help_text='Athlete association.', max_length=1000, null=True, verbose_name='Athlete association')),
                ('style', models.CharField(blank=True, help_text='Presentation style.', max_length=1000, null=True, verbose_name='Presentation style')),
            ],
            options={
                'verbose_name': 'Athlete',
                'verbose_name_plural': 'Athletes',
            },
        ),
        migrations.CreateModel(
            name='Formula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(help_text='formula description.', max_length=1000, verbose_name='formula description')),
                ('formula', models.CharField(help_text='formula.', max_length=1000, verbose_name='formula')),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indenfification', models.CharField(help_text='tournament indenfification.', max_length=1000, verbose_name='tournament indenfification')),
                ('date', models.DateTimeField(help_text='tournament date.', verbose_name='tournament date')),
            ],
            options={
                'verbose_name': 'Tournament',
                'verbose_name_plural': 'Tournaments',
            },
        ),
        migrations.CreateModel(
            name='TypeGrades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(help_text='Types of notes.', max_length=1000, verbose_name='Types of notes')),
            ],
        ),
        migrations.CreateModel(
            name='Grades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.DecimalField(decimal_places=2, help_text='Grade', max_digits=10, verbose_name='Grade')),
                ('validation', models.BooleanField(help_text='score validation by the head judge', verbose_name='score validation')),
                ('athlete', models.ForeignKey(blank=True, help_text='athlete to whom the grade will be assigned.', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.athlete', verbose_name='Athlete')),
                ('tournament', models.ForeignKey(blank=True, help_text='tournament the athlete is participating in.', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.tournament', verbose_name='Tournament')),
                ('type_grate', models.ForeignKey(blank=True, help_text='Type grades.', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.typegrades', verbose_name='Type grades')),
            ],
            options={
                'verbose_name': 'Grades',
                'verbose_name_plural': 'Grades',
            },
        ),
        migrations.CreateModel(
            name='Deductions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deductions', models.DecimalField(decimal_places=2, help_text='deductions', max_digits=10, verbose_name='deductions')),
                ('athlete', models.ForeignKey(blank=True, help_text='athlete to whom the deduction will be assigned.', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.athlete', verbose_name='Athlete')),
                ('tournament', models.ForeignKey(blank=True, help_text='tournament the athlete is participating in.', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.tournament', verbose_name='Tournament')),
            ],
            options={
                'verbose_name': 'Deductions',
                'verbose_name_plural': 'Deductions',
            },
        ),
    ]
